---
title: "Blog Posts, Research and Interviews in Popular Media"
description: |
  See below for some helpful resources and interesting stories from the B.E.A.V.E.R.S lab.
output: distill::distill_article
---

## -Blog posts about publishing- ##

Stoops W.W., Pang R.D., Bradford D.E. (2021, September 23). Publishing in a scholarly journal: Part one, the publishing process.
[Link](https://www.apa.org/pubs/journals/resources/publishing-tips/publishing-process)

Stoops W.W., Pang R.D., Bradford D.E. (2021, September 23). Publishing in a scholarly journal: Part two, role of the editorial board. [Link](https://www.apa.org/pubs/journals/resources/publishing-tips/editorial-board)

Stoops W.W., Pang R.D., Bradford D.E. (2021, September 23). Publishing in a scholarly journal: Part three, peer review. [Link](https://www.apa.org/pubs/journals/resources/publishing-tips/peer-review)

## -Research and interviews in the news- ###

Pappas, S. (2022, June 1). With traffic deaths on the rise, psychologists are being called on to make driving safer. [APA Monitor](https://www.apa.org/monitor/2022/06/feature-traffic-safety)

Rosbach, M. (2022, January 22). OSU Research: How alcohol dampens response to uncertain stressors [Web log post](https://www.thechronicleonline.com/news/osu-research-how-alcohol-dampens-response-to-uncertainstressors/article_89f0db16-7a3a-11ec-92c9-0747d3b67c1f.html)

Sara Gavin. (2018, November, 12) How alcohol dilutes anxiety [Web log post](https://today.umd.edu/articles/how-alcohol-dilutes-anxiety-f958169c-f9ba-41eb-bc60-aa6bd24409c0)

Job de Vrieze. (2018, January, 18). Nearly 100 scientists spent 2 months on Google Docs to redefine the p-value. Here’s what they came up with [Web log post](http://www.sciencemag.org/news/2018/01/nearly100-scientists-spent-2-months-google-docs-redefine-p-value-here-s-what-they-came)

Cindy Lamothe. (2017, August, 9). An Alarming Number of People Don’t Know the Signs of Prescription-Drug
Abuse [Web log post](https://www.thecut.com/2017/08/opioid-epidemic-addiction-mental-health.html?fbclid=IwAR2IuHPLedPm1MbfVCGeFs-lD0XdMvpAbF-kHvNW20IX6S8CBGJq9-faiS8)

Emily Cassel. (2017, June, 2). Painkiller addictions are the easiest to hide [Web log post](https://tonic.vice.com/en_us/article/3kzn49/painkiller-addictions-are-the-easiest-to-hide)

Christian Jarrett. (2017, March, 26). 5 Studies to help explain why social drinking is so rewarding [Web log post](http://www.businessinsider.com/5-studies-that-help-explain-why-social-drinking-is-so-rewarding2017-3)

Julie Spitzer. (2017, February, 13). How substances affect the human brain and why we become addicted [Web log post](http://www.dailycardinal.com/article/2017/02/how-substances-affect-the-human-brainand-why-we-become-addicted)

Wray Herbert. (2013, July, 22). Booze, binging, and the devil you don’t know. [Web log post](http://www.huffingtonpost.com/wray-herbert/booze-binging-and-the-dev_b_3634559.html)

Alcohol dampens stress responses, especially for uncertain threat. [Web log post](http://www.psychologicalscience.org/index.php/publications/observer/obsonline/alcohol-dampens-stressresponses-especially-for-uncertain-threats.html)



