---
title: "Joining the lab as an undergraduate"
description: |
output: distill::distill_article
---
---
title: "Joining the lab as an undergraduate"
description: 
  ""
---
As a new lab on campus, we are looking for 1-2 undergraduate research assistants (RAs) to help us set up a sophisticated and involved psychophysiology laboratory. **As of October 2021, we are only accepting applications for students interested in doing research on a volunteer basis. This will likely change after Fall term.**

Your responsibilities may include:

* Organizational tasks
* Assisting in literature review
* Manual set up of laboratory equipment
* Assisting/providing feedback for lab protocol development

Why should you consider joining our lab?

* You will gain a unique and invaluable opportunity to set up a brand-new psychophysiological laboratory, eligible to be placed on your resume or CV
* Begin networking with leading researchers in the addiction and anxiety psychophysiological research field.
* As one of the first people setting up the lab, you will likely have opportunity to provide feedback to and input in various facets of cohesive lab functioning.

**If you have any questions, please don’t hesitate to contact Angelica DeFalco at angelica.defalco@oregonstate.edu or Daniel Bradford at daniel.bradford@oregonstate.edu**

If you are interested in applying, fill out [this](https://forms.gle/XK2cDVEQQUsqxxgPA) google form. Please give us at least a week to review your application before scheduling an interview.





