---
title: "Lab Values"
description: 
  "Our lab is committed to equity and social justice. Much of our statement on lab values is inspired/borrowed from my colleague and good friend, [Dr. Fallon Goodman's](https://www.fallongoodman.com/) lab."
---

Though science is fun and exciting, it can also be hard and stressful. Individuals also have their own unique challenges intrinsic to their circumstance. Our lab is committed to viewing each member as a whole person with a life both inside and outside of the lab. We operate from the assumption that in a person’s life—and perhaps during their time in our lab—there will be significant life stressors. Our mindset is that in order to have successful and meaningful careers, these stressors cannot be ignored. Rather, each individual and all of their stories are to be accepted and integrated in the fiber of our lab. By joining the lab, you are committing to the spirit of this community and its fellow lab members.

**Dr Bradford’s mentoring style:**  

As the director of this lab, I am committed to supporting each member first and foremost as a complex, evolving, human being. I prioritize being available to lab members during both regular and often non-regular hours. In my view, this availability does not end when a lab member graduates or moves out of the state. I stay connected to many of my previous mentees for many years after the formal mentoring relationship has completed. I believe it is a mentor’s responsibility to be flexible and adjust to mentee’s needs within the mentoring relationship. This adjustment includes both the mentor and mentee finding the best way to communicate with one another. None of this means that I will not encourage lab members to grow and become independent. In fact, I have high expectations for and place large responsibility on lab members. I simply commit to supporting lab members as they carry and foster those expectations and responsibility.  

The science we do in the lab is complex. I believe it is crucial to present this material in the clearest possible way. Despite some of the words used in the research descriptions on this website, I am careful to avoid scientific jargon and make attempts to use plain language in the lab. While helping lab members to strive for a fuller understanding of the data they consume, I encourage them to look for bias in the ways data may be presented in media reports that can obscure important shortcomings or caveats to our and others’ research.  

I am very proud to have been fortunate enough to have my mentoring recognized several times. I received the 2017 Excellence in Undergraduate Mentoring Award from the Office of the Provost at University of Wisconsin, Madison. My contributions to mentoring students from diverse backgrounds was also recognized by the Multicultural Graduate Network with an honorable mention for their Peer Mentor Award. In 2021, I was awarded both the University of Miami Graduate Faculty Mentor of the Year award and the Psychology Graduate Student Organization Teacher of the Year award. I am new to Oregon State University as of January 2022 so I am happy to provide references to my mentoring by mentees from my previous universities.  

**Reproducibility, Rigor, Transparency, Equity, and Openness:**  

Fifteen years ago, during a heated debate, my coworker angrily spoke words that still echo in my mind: “Psychology is a pseudoscience.” These words illustrate a common stigma that psychology’s merit is not up to par with the hard sciences, something that threatens the standing of psychological research in the public eye. Today, this threat is amplified by widespread concerns about the reproducibility of psychological science and more broadly, societal shifts towards a “post truth era.” Unfortunately, negative public perception about psychology can also discourage people from seeking much-needed psychological treatment. Consequently, stigma surrounding mental illness persists. Our lab is committed to fighting these issues, among others, through doing careful, rigorous, and transparent science. We aim to increase our understanding of human behavior while simultaneously remaining critical consumers and reliable disseminators of research. Most of our research is programmatic meaning we do multiple studies on the same topic and use careful internal replications. For many of our studies, we preregister our analysis parameters and openly share our data and analysis code.  

**Skills and experiences you can gain in our lab:**  

If you are in the lab for at least two semesters, you will have the opportunity to receive instruction and gain valuable experience using multiple tools used in clinical and experimental psychology including both software such as R statistical computing platform and MATLAB as well as psychophysiology measurement techniques such as Electroencephalogram (EEG), Event Related Potentials (ERP), Electromyography (EMG) and Electrode Dermal Analysis (EDA). You will also likely have the opportunity to learn psychopharmacology techniques such as safe dosing of ethyl alcohol and measurement of Blood Alcohol Content (BAC). All of these skills will be taught with an eye to Open Science practices.


---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

